version: "3.8"

services:
  nextjs:
    container_name: nextjs
    build:
      context: .
      dockerfile: ./docker/next/Dockerfile
      target: development
    volumes:
      - "./:/app/"
    ports:
      - "3000:3000"
